export const ADD_DATA_REQUEST = ' ADD_DATA_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';

export const FETCH_DATA_REQUEST = ' FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_REQUEST = ' UPDATE_DATA_REQUEST';
export const UPDATE_DATA_FAILURE = 'UPDATE_DATA_FAILURE';

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';